/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // mac专区
  mac专区: [{ type:'autogenerated', dirName: 'mac专区'}],

  // devops
  devops: [{type: 'autogenerated', dirName: 'Linux/devops' }],
  ansible: [{type: 'autogenerated', dirName: 'Linux/devops/ansible' }],
  gitea: [{type: 'autogenerated', dirName: 'Linux/devops/gitea' }],
  gitlab: [{type: 'autogenerated', dirName: 'Linux/devops/gitlab' }],
  jenkins: [{type: 'autogenerated', dirName: 'Linux/devops/jenkins' }],
  spug: [{type: 'autogenerated', dirName: 'Linux/devops/spug' }],
  walle: [{type: 'autogenerated', dirName: 'Linux/devops/walle' }],

  // 云原生
  云原生: [{ type: 'autogenerated', dirName: '云原生/k8s'}],
  云原生工具: [{ type: 'autogenerated', dirName: '云原生/云原生工具'}],
  容器: [{ type: 'autogenerated', dirName: '云原生/容器'}],
  
  // 编程
  go: [{ type: 'autogenerated', dirName: '编程/go'}],
  python: [{ type: 'autogenerated', dirName: '编程/python'}],
  shell: [{type: 'autogenerated', dirName: '编程/shell'}],
  script: [{type: 'autogenerated', dirName: '编程/功能脚本'}],

  // Linux
  Linux服务: [{ type: 'autogenerated', dirName: 'Linux/Linux服务'}],
  Linux命令: [{ type: 'autogenerated', dirName: 'Linux/Linux命令'}],
  Linux系统: [{ type: 'autogenerated', dirName: 'Linux/Linux系统'}],

  // 监控
  prometheus: [{ type: 'autogenerated', dirName: 'Linux/监控/prometheus'}],
  zabbix: [{ type: 'autogenerated', dirName: 'Linux/监控/zabbix'}],
  grafana: [{ type: 'autogenerated', dirName: 'Linux/监控/grafana'}],
  nightingale: [{ type: 'autogenerated', dirName: 'Linux/监控/nightingale'}],

  // 数据库
  mongodb: [{ type: 'autogenerated', dirName: '数据库/mongodb'}],
  mysql: [{ type: 'autogenerated', dirName: '数据库/mysql'}],
  redis: [{ type: 'autogenerated', dirName: '数据库/redis'}],
  postgres: [{ type: 'autogenerated', dirName: '数据库/postgres'}],  

  // 云厂商知识点
  阿里云: [{ type: 'autogenerated', dirName: '云厂商知识点/阿里云'}],
  腾讯云: [{ type: 'autogenerated', dirName: '云厂商知识点/腾讯云'}],
  aws: [{ type: 'autogenerated', dirName: '云厂商知识点/aws'}],

  // AI
  LLM工程平台: [{ type: 'autogenerated', dirName: 'AI/LLM工程平台'}],
  AI应用可视化平台: [{ type: 'autogenerated', dirName: 'AI/AI应用可视化平台'}],

};

module.exports = sidebars;