name: Deploy Docusaurus

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        id: build
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      # =========================
      # ✅ 成功通知
      # =========================
      - name: Notify Success
        if: success()
        run: |
          curl "${{ secrets.WECHAT_WEBHOOK }}" \
          -H 'Content-Type: application/json' \
          -d '{
                "msgtype": "markdown",
                "markdown": {
                  "content": "# 🚀 发布结果通知\n\n发布类型：Branch 发布\n申请标题：${{ github.event.head_commit.message }}\n应用名称：${{ github.repository }}\n版本标识：${{ github.ref_name }}#${{ github.sha }}\n执行人员：${{ github.actor }}\n发布结果：<font color=\"info\">发布成功</font>"
                }
              }'

      # =========================
      # ❌ 失败通知
      # =========================
      - name: Notify Failure
        if: failure()
        run: |
          curl "${{ secrets.WECHAT_WEBHOOK }}" \
          -H 'Content-Type: application/json' \
          -d '{
                "msgtype": "markdown",
                "markdown": {
                  "content": "# 🚀 发布结果通知\n\n发布类型：Branch 发布\n申请标题：${{ github.event.head_commit.message }}\n应用名称：${{ github.repository }}\n版本标识：${{ github.ref_name }}#${{ github.sha }}\n执行人员：${{ github.actor }}\n发布结果：<font color=\"warning\">发布失败</font>"
                }
              }'